version: "2"
run:
  go: "1.24"
linters:
  default: none
  enable:
    - nilnil
  settings:
      nilnil:
        only-two: false
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
